version: '3.8'

services:
  github-runner:
    build: .
    environment:
      - GITHUB_URL=${GITHUB_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME:-self-hosted-runner}
      - RUNNER_LABELS=${RUNNER_LABELS:-self-hosted,Linux,Docker}
      - RUNNER_WORK_DIRECTORY=${RUNNER_WORK_DIRECTORY:-_work}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/home/runner
    restart: unless-stopped

volumes:
  runner_data: 